version: '3'

services:
  leshan:
    image: ${ACCOUNT:-foundriesio}/leshan:latest
    read_only: true
    environment:
     - LESHAN_ARGS=-wp 8081
    ports:
      - "8081:8081"
      - "5683:5683/udp"
      - "5684:5684/udp"
      - "5685:5685/udp"
      - "5686:5686/udp"
    restart: always
    tmpfs:
      - /tmp
  networks:
    - big-network

  hawkbit:
    image: ${ACCOUNT:-foundriesio}/hawkbit-update-server:latest
    read_only: true
    ports:
      - "8080:8080"
    restart: always
    tmpfs:
      - /var/run
      - /var/cache/nginx
      - /tmp
    networks:
      - big-network

  mosquitto:
    image: ${ACCOUNT:-foundriesio}/simple-mosquitto-broker:latest
    read_only: true
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: always
    networks:
      - big-network

  bt-joiner:
    image: ${ACCOUNT:-foundriesio}/simple-bt-joiner:latest
    tmpfs:
      - /run
      - /var/lock
      - /var/log
      - /var/run
    network_mode: "host"
    restart: always
    read_only: true
    privileged: true

  simple-californium-proxy:
    image: ${ACCOUNT:-foundriesio}/simple-californium-proxy:latest
    read_only: true
    ports:
      - "5682:5682"
    networks:
      - big-network
    restart: always

networks:
  big-network:
